[git_branch]
symbol = ""

[git_status]
conflicted = "ğŸ³"
behind = "â—ï¸"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
stashed = "ğŸ“¦"

[character]
success_symbol = "[ğŸ¦‰ ](bold green)"
error_symbol = "[ğŸ¶ ](bold red)"