[git_status]
conflicted = "ğŸ³"
behind = "â—ï¸"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
stashed = "ğŸ“¦"
untracked = "U"

[character]
success_symbol = "[ğŸ–](bold green)"
# success_symbol = "[â¯](green)[â¯](red)[â¯](white)"
error_symbol = "[ğŸ¶](bold red)"

